sudo: false
language: rust
# necessary for `travis-cargo coveralls --no-sudo`
addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev

rust:
  - nightly

before_script:
  - |
      pip install 'travis-cargo<0.2' --user &&
      export PATH=$HOME/.local/bin:$PATH

script:
  - |
      travis-cargo build &&
      travis-cargo test &&
      travis-cargo test -- --release &&
      travis-cargo bench &&
      travis-cargo doc
after_success:
  - travis-cargo doc-upload
  - travis-cargo coveralls --no-sudo

env:
  global:
    - secure: "BnS2XFH4zGeJxqF2m6mlDu3+J4LRZFhiEm/i3ft60YVf5gMHkwfHnmutwFHM2u7M1vwQwJ/I5YpOBW96PPWozQA2mTs9nuOyfxeiKYg0XAcZzA7osLYTXhwWi+9CGAbdFO26aJDuuC3/gqjojlNly0MkSuMR0rrFJGSxCZfZrqIKS8H0LRE/BGe3rUTPdFUhFrHS54NjD48ksXBhM6sc1fhuYH7NSBirgzZ5ah284GQ4WRRf3cH4m10bStu19XpgLgcmJYj56WyDXAI19y3ztlzN/dtz+XJHRnFIGUbCY2FlsiPdmsmgiIoJrdZ8OJV3RyjyEn0c++VtRq3ax9VG0Ro2n8n3OSDuTorcWAE2Zgljg0HMGkCI2RUC35YHn5WbHJQKitipyNsDUjm2/UI1evf0vB5x4AyOaPfmrA88Esak20WvDLhZdwZ9Y7gCYT4v/TxSJgFcsTjpY08dwtApThQOUl7UtyPf6mU3pmMinQQi5Ki5C/dfn689YPLyr//dtXPTITQXqcr2NzoHdqVTLDGqtP1bnazQ/tF1EkQuCOKgpUxMwT1a0gQp+4dyX09aEZwZ2tYM5XoPi6uXg6bYHJZ/zH1n1+fJm0b5m+w7TVRkAqt2JXc1ZuEdO6GDEi5hwU7l7SaEN3XpDVPfoG6FY8zXC+emlJEODkG+9TZfn+M="
