sudo: false
language: rust
# necessary for `travis-cargo coveralls --no-sudo`
addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev

rust:
  - nightly

before_script:
  - |
      pip install 'travis-cargo<0.2' --user &&
      export PATH=$HOME/.local/bin:$PATH

script:
  - |
      travis-cargo build &&
      travis-cargo test &&
      travis-cargo test -- --release &&
      travis-cargo bench &&
      travis-cargo doc
after_success:
  - travis-cargo doc-upload
  - travis-cargo coveralls --no-sudo

env:
  global:
    - secure: "To4jmVsAYX4pXc4OUvcJNY0B6L6XyFzqRCR7q5py7RPLOs9clU2uCfyAHYqBMp6KvFrE4BRwHx6Fp21GT67GnPx8h/qaVFHCRtwdhehLafdw45qtVhTkGOJDqDVTiUggIxldyO9H16ucl6Ka5bghM1DgeJcQ35SROs9+reQnPusPAAOHbkAUruM2wOqmvFStxhxnz0R7UjIsRCIgh/sNcEir5IRA/Y6GeEAReZrELW8XzzBj9Ay1lc3Q7vjcIEykR4UaVCuHo3TAoGtGJKpWOX0khpHgoenDZaIyBHYy0zCI5ZwhXXUfLFh9SsW9u7stbgiNzc1KWYYiGB9R42WL3VkDLXoPvWOwnYsCWyoaom14qFE0xb+xYODvWqlOBUK1kyiPuJjVzllR1Xcr+chNeha9icMKPyFZQVweQz8VwSmhf6hZOY/pnJrbmI9avcYV++0UiKXlqISXImr6ql3zHLx6LE7b3SmPVwT9K7zuDGZ9UPv2hydZ3nne+e0dZBRXU5cEtDWQ5bTiPlJv/0T9qtQu5eHgJKPaBj+ICoRecJ4HdwoQ3A8fNwzaZwO24lmtFzXflZGKAqAsiAiE5J1a1RkJ1VaWTb24X+9xywJvy4q8k77tLexvqVIApERJGMDFJPwnFpKYIABdc/ROee/tz1a2itAeGqjN23VAW4K7qyM="
